project:
  type: website

website:
  title: "Wojciech"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

  sidebar:
    style: "docked"     
    search: true
    contents:
      - section: "Machine Learning"
        contents:
          - href: wl-tune-bayes-parallel.qmd
            text: Bayesian Tune
          - href: wl-infer-4.qmd
            text: K-means clustering and statistical inference
          - href: wl-fe.qmd
            text: FE for the XGBoost model using Cramér's V and Eta Square tests
          - href: wl-clustering-infer-2.qmd
            text: K-means clustering and statistical inference - diamonds datase
          - href: vip_end.qmd
            text: Determining feature importance using the vip::vip function
          - href: KMEANS_FLINK.qmd
            text: Calculating the number of clusters and distances from centroids for the KMEANS model in fraud detection
      - section: "Data Analysis"
        contents:
          - href: quakes_v7.qmd
            text: Analysis of earthquake data using Plotly  
          - href: cu_color_v5.qmd
            text: Analysis of the influence of features on the cut and color of diamonds 
      - section: "Data Analysis and Data Engineering"
        contents:
          - href: msfabric_v2.qmd
            text: Microsoft Fabric - End-to-End Diamond Sales Analytics Platform using ELT pipeline, Power BI and Tableau Public
          - href: lakehouse_v1.qmd
            text: Lakehouse Data Analytics Platform - Microsoft Fabric Cloud - PySpark - SparkR
          - href: KafkaFabric_v1.qmd
            text: Online store transaction monitoring system using Real-Time Dashboard (Microsoft Fabric)
          - href: Kafka_Scalability.qmd
            text: Scalability and data replication in Kafka - testing the resilience of a Kafka cluster to broker host failures. Cassandra and Kafka Connect basics
          - href: kappa_v1.qmd
            text: Data Architecture example with Airflow, dbt, ClickHouse, Kafka with an automatic report generator in Pandas and Seaborn that automatically sends reports to Jira

          

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

